spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/sifap}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sifap}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:sifap_local}